name: Python build

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    # - name: Test with pytest
    #   run: |
    #      if [[ dpkg -s pytest -eq 1 && -f tests ]]; then python -m pytest --import-mode=append tests/; fi      
    - name: Create source distribution file
      run: |
        pkgcheck=$(dpkg -s wheel)
        if [ $pkgcheck -eq 1]; python3 -m build -wheel; fi
